- name: copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: deamon reload and start
  ansible.builtin.systemd_service:
    damon_reload: true

- name: start ands enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes