- name: copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: deamon reload and start
  ansible.builtin.systemd_service:
    deamon_reload: true

- name: "start ands enable {{component}}""
  ansible.builtin.service:
    name: "{{component}}""
    state: restarted
    enabled: yes