- name: copy catalogue service
  ansible.builtin.copy:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: deamon reload and start
  ansible.builtin.systemd_service:
    deamon_reload: true

- name: "start ands enable {{component}}""
  ansible.builtin.service:
    name: "{{component}}""
    state: restarted
    enabled: yes